server {
    listen 80;
    server_name localhost;

    # Laravel debe apuntar a /public
    root /var/www/public;
    index index.php index.html;

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # --- GZIP ---
    gzip on;
    gzip_min_length 100;
    gzip_vary on;
    gzip_static on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss;

    # Rutas normales
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    # Ejecutar PHP via PHP-FPM (Corregido a una sola barra para la expresión regular)
    location ~ \.php$ {
        # Si el archivo no existe, 404
        try_files $uri =404;

        # Corregido a una sola barra invertida
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # "app" debe coincidir con el nombre del servicio en docker-compose
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
